### ISSUE TITLE
Error: image library/sentora:latest not found

### ISSUE THREAD

**Issue by bhcopeland** [yofreke/docker-sentora#1]
(theses passwords are saved in /root/passwords.txt)
###### 

Restart your server now to complete the install (y/n)? y
shutdown: Unable to shutdown system
127 ben@desky ~/Downloads/docker-sentora (git)-[master] % ./start-sentora-container.sh                              :(
Unable to find image 'sentora:latest' locally
Pulling repository sentora
Error: image library/sentora:latest not found

Because I said "yes" to the restart, it caused a exit code of 1 and docker image wasnt created.

**Comment by yofreke** [comment]
True, this is a shortcoming of the current implementation.  This will hopefully be improved in the future.

> Once inside the container, follow instructions, and do not press 'y' when asked to reboot
