### ISSUE TITLE
Database partition is full

### ISSUE THREAD

**Issue by Nodemio** [yofreke/docker-sentora#3]
the service is down in production... message "/etc/init.d/mysql: ERROR: The partition with /var/lib/mysql is too full!
" 
WTF???

**Comment by yofreke** [comment]
How much space is left on your hard drive?  The version of sentora on this repo is super old, we actually ran in to a few security vulnerabilities that ended up in a virus sending _tons_ of spam emails, which would fill up dovecot logs as well as the mail spools.

Make sure you hard drive still has space, then make sure that you are not sending tons of spam emails :/

**Comment by Nodemio** [comment]
thanks for the reply , you must close this commit, since it was a particular problem for my own server and not the repository.
